# Generated by Django 2.1.7 on 2019-05-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('accuracy', models.CharField(max_length=200)),
                ('submssions', models.CharField(max_length=200)),
                ('submit_url', models.CharField(max_length=200)),
                ('question_type', models.CharField(max_length=200)),
            ],
        ),
    ]
